### ISSUE TITLE
Possible mismatch in assigning sample container capacity

### ISSUE THREAD

**Issue by simonpecher** [kairos-fhir/kairos-fhir-dsl-mapping-example#36]
Hi,

using the script `src/main/groovy/projects/cxx/v2/specimen.groovy` as a template, I encountered a mismatch of the container capacity value and its unit because this assignment 
https://github.com/kairos-fhir/kairos-fhir-dsl-mapping-example/blob/e117fdb104f950f11a47ae129aa67ed3c4aa55ce/src/main/groovy/projects/cxx/v2/specimen.groovy#L117

doesn't seem to correspond to ` value = context.source[sample().receptable().size()]`

For the MII biobanking module the assigment is as expected:

https://github.com/kairos-fhir/kairos-fhir-dsl-mapping-example/blob/e117fdb104f950f11a47ae129aa67ed3c4aa55ce/src/main/groovy/projects/mii/modul/biobanking/specimen.groovy#L124

Is there a reason for this difference?

Thank you

**Comment by kairosmike** [comment]
The full capacity element has been removed from the dktk specimen script within commit [eee576479b6f1120d80299186421eac15578d914](https://github.com/kairos-fhir/kairos-fhir-dsl-mapping-example/commit/eee576479b6f1120d80299186421eac15578d914) already in 2022.
The question seems to be obsolete.
